### ISSUE TITLE
Bug with Shorah wrapper

### ISSUE THREAD

**Issue by jblamyatifremer** [cbg-ethz/shorah#27]
Dear Shorah creators, 

We struggle since two weeks on shorah... we always get the same error. We have tested shorah on two linux plateforme (Ubuntu 12.04 and Fedora 25) and bam file from Bowtie or BWA-MEM aligners.

I should mention that we are working on DNA virus with 200 kb with large deletions and shorah was not design for such virus (but we suspect that intra-population virus diversity play an important role in our biological system)

##---------------------------------------------------------------------------------------------------------
## subset bam files (we have a big bam file with large deletions >2000 bp )
samtools view /media/jean-baptiste/FREECOM/OshV1/00_raw_data/LI/LI_537108089.sorted.bam -T /media/jean-baptiste/FREECOM/OshV1/00_raw_data/references/537108089_complet.fasta -o /media/jean-baptiste/FREECOM/OshV1/01_parse_bam/LI_537108089.sorted.parse_60-62bp.bam region "gi|537108089|ref|NC_005881.2|":60000-62000

## index bam file
samtools index -b /media/jean-baptiste/FREECOM/OshV1/01_parse_bam/LI_537108089.sorted.parse_60-62bp.bam

## launch shorah on a smaller regions (without indels)
/home/jean-baptiste/shorah-master/shorah.py -b /media/jean-baptiste/FREECOM/OshV1/01_parse_bam/LI_537108089.sorted.parse_60-62bp.bam -f /media/jean-baptiste/FREECOM/OshV1/00_raw_data/references/537108089_complet.fasta -w 99 -r 'gi\|537108089\|ref\|NC_005881.2\|':60000-62000

{0: 67309} ## we don't understood those bounds since it does not match our regions
Traceback (most recent call last):
  File "/home/jean-baptiste/shorah-master/shorah.py", line 142, in <module>
    keep_files=options.k, alpha=options.a)
  File "/home/jean-baptiste/shorah-master/dec.py", line 561, in main
    (kp, float(proposed[kp][0]) / proposed[kp][1]))
ValueError: could not convert string to float: not found

##---------------------------------------------------------------------------------------------------------

Here an adress with all needed datasets to reproduce the error (copy/paste the adress in web browser)

https://filesender.renater.fr/?s=download&token=63db9bac-91ee-d285-55ef-b5d46479b4fa

The file will last until 10 of may 2017.

Cheers

JB

**Comment by ozagordi** [comment]
Hi,
are you running the newest 1.0 version?

I just ran
`shorah.py -b LI_537108089.sorted.parse_60-62bp.bam -f 537108089_complet.fasta -w 99 -r 'gi\|537108089\|ref\|NC_005881.2\|':60000-62000`

to see if I can figure out what happens.


Two potential problems:
1. pipes in reference sequence name can create problems. It has happened before and I would suggest you to change them to some harmless character like underscore. While running, for example, I had 31 `diri_sampler` processes, but I could only see one `smp` file;
2. there is a marked drop in the coverage in the middle of the region, from ~1000 to <100
```
 cut -f 1,5 coverage.txt
...
w-gi|537108089|ref|NC_005881.2|-60627-60725.reads.fas	1802
w-gi|537108089|ref|NC_005881.2|-60660-60758.reads.fas	1156
w-gi|537108089|ref|NC_005881.2|-60726-60824.reads.fas	91
w-gi|537108089|ref|NC_005881.2|-60759-60857.reads.fas	1586
w-gi|537108089|ref|NC_005881.2|-60792-60890.reads.fas	1408
...
```
This sudden drop in the coverage has been observed to cause errors.

That said, `dec.py` runs `diri_sampler` and then analyzes the results to correct reads. `shorah.py`, at least for now, also runs global reconstruction (it will be dropped in a future update). My `dec.py` ran `diri_sampler` without problems on all windows, and I now have a `support` folder (and others) with my output. But I have a lot of "No reads in window w?" and " this is window w--w-gi|537108089|ref|NC_005881" in the log file, without position numbers. This might be due to the naming of the read files that uses the reference, and pipes might disturb this scheming.

I would proceed as follows, just to make sure we are on the same track. Please install the latest version from the release page, change the name of the reference file replacing `|` with `_` and align  again.

Then, do you really need global reconstruction? If yes, other tools might suit you better (quasirecomb, haploclique, what do you think @SoapZA?). If not, just run `dec.py` rather than `shorah.py`.

Let me know.

Best.
    Osvaldo

**Comment by SoapZA** [comment]
I agree with @ozagordi here. Global reconstruction with ShoRAH is generally a lost cause, as other algorithms are better at taking long range co-occurrences into account. ShoRAH's strengths have always been it's sensitive error correction with its non-parametric clustering.

**Comment by jblamyatifremer** [comment]
Hi Shorah creators, 

Waou... quick responses ! We are running the lastest version of Shorah (but i will double check it) 
I will try our suggestions about the reference file name and filter out the drop of coverage (double check the MapQ of such reads)

I really need the global reconstruction for my biological question and we are currently working on both Haploclique and QuasiRecom to compare the outputs. 

I will keep you in touch before the end of the week. 

JB

**Comment by ozagordi** [comment]
Hi @jblamyatifremer. Any news on this issue, or should we close it?

**Comment by jblamyatifremer** [comment]
Yes, you could close it. 
Conclusion : 
We have large deletions in the genome that causes the crash of Shorah, maybe it would be nice to rename the post to be more specific :  
"Large deletion and drop in coverage causes shorah to stop"
